# Generated by Django 4.0.6 on 2022-08-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='educationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=50, null=True, verbose_name='Institution Name')),
                ('date_of_joining', models.DateField(null=True, verbose_name='Date of Joining')),
                ('date_of_leaving', models.DateField(null=True, verbose_name='Date of Joining')),
            ],
        ),
    ]
