# Generated by Django 4.0.6 on 2022-08-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='experienceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50, null=True, verbose_name='Company Name')),
                ('date_of_joining', models.DateField(null=True, verbose_name='Date of Joining')),
                ('date_of_leaving', models.DateField(null=True, verbose_name='Date of Joining')),
            ],
            options={
                'verbose_name_plural': 'Experience Details',
            },
        ),
        migrations.AlterModelOptions(
            name='educationdetails',
            options={'verbose_name_plural': 'Education Details'},
        ),
    ]
