# Generated by Django 4.0.6 on 2022-08-08 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_experiencedetails_alter_educationdetails_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationdetails',
            name='course_studied',
            field=models.CharField(max_length=50, null=True, verbose_name='Course Studied'),
        ),
        migrations.AddField(
            model_name='experiencedetails',
            name='position',
            field=models.CharField(max_length=50, null='True', verbose_name='Position'),
            preserve_default='True',
        ),
    ]
