# Generated by Django 4.0.6 on 2022-08-10 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_educationdetails_course_studied_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationdetails',
            name='card_color',
            field=models.CharField(choices=[('1', 'b-success'), ('2', 'b-danger'), ('3', 'b-warning'), ('4', 'b-info')], max_length=50, null=True, verbose_name='Flashcard Color'),
        ),
    ]
