# Generated by Django 4.0.6 on 2022-08-10 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_experiencedetails_card_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationdetails',
            name='date_of_joining',
        ),
        migrations.RemoveField(
            model_name='educationdetails',
            name='date_of_leaving',
        ),
        migrations.AddField(
            model_name='educationdetails',
            name='year_of_joining',
            field=models.CharField(max_length=50, null=True, verbose_name='From'),
        ),
        migrations.AddField(
            model_name='educationdetails',
            name='year_of_leaving',
            field=models.CharField(max_length=50, null=True, verbose_name='To'),
        ),
    ]
