# Generated by Django 4.0.6 on 2022-08-10 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_remove_educationdetails_date_of_joining_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiencedetails',
            name='date_of_joining',
        ),
        migrations.RemoveField(
            model_name='experiencedetails',
            name='date_of_leaving',
        ),
        migrations.AddField(
            model_name='experiencedetails',
            name='year_of_joining',
            field=models.CharField(max_length=50, null=True, verbose_name='From'),
        ),
        migrations.AddField(
            model_name='experiencedetails',
            name='year_of_leaving',
            field=models.CharField(max_length=50, null=True, verbose_name='To'),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='card_color',
            field=models.CharField(choices=[('1', 'Green'), ('2', 'Red'), ('3', 'Yellow'), ('4', 'Light Blue')], max_length=50, null=True, verbose_name='Flashcard Color'),
        ),
        migrations.AlterField(
            model_name='experiencedetails',
            name='card_color',
            field=models.CharField(choices=[('1', 'Green'), ('2', 'Red'), ('3', 'Yellow'), ('4', 'Light Blue')], max_length=50, null=True, verbose_name='Flashcard Color'),
        ),
    ]
