# Generated by Django 4.0.6 on 2022-08-10 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_alter_educationdetails_card_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationdetails',
            name='card_color',
            field=models.CharField(choices=[('b-success', 'Green'), ('b-danger', 'Red'), ('b-warning', 'Yellow'), ('b-info', 'Light Blue')], max_length=50, null=True, verbose_name='Flashcard Color'),
        ),
        migrations.AlterField(
            model_name='experiencedetails',
            name='card_color',
            field=models.CharField(choices=[('b-success', 'Green'), ('b-danger', 'Red'), ('b-warning', 'Yellow'), ('b-info', 'Light Blue')], max_length=50, null=True, verbose_name='Flashcard Color'),
        ),
    ]
