# Generated by Django 4.0.6 on 2022-09-23 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_alter_projects_options_projects_about_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='technologies_used',
            field=models.TextField(null=True, verbose_name='Technologies Used'),
        ),
    ]
