# Generated by Django 4.0.6 on 2022-09-23 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_projects_technologies_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='technologies_used',
            field=models.TextField(null=True, verbose_name='Technologies Used (Use comma to separate the words)'),
        ),
    ]
